# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='img',
            field=models.FileField(upload_to='uploads/firms', verbose_name='Картинка фирмы'),
        ),
    ]
