# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170416_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория, которой принадлежит фирма'),
        ),
    ]
