# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория, которой принадлежит коллекция'),
        ),
    ]
