# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170416_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='short_name',
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_10',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_11',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_12',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_13',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_14',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_15',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_16',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_17',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_18',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_19',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_20',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_21',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_22',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_23',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_24',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_25',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_26',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_27',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_28',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_29',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_30',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_31',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_32',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_33',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_34',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_35',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_36',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_37',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_38',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_39',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_4',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_40',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_41',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_42',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_43',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_44',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_45',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_46',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_47',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_48',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_49',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_5',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_50',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_51',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_52',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_53',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_54',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_55',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_56',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_57',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_58',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_59',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_6',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_60',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_7',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_8',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='img_sample_9',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_11',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_13',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_14',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_15',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_16',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_17',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_18',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_19',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_20',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_21',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_22',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_23',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_24',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_25',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_26',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_27',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_28',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_29',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_30',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_31',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_32',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_33',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_34',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_35',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_36',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_37',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_38',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_39',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_40',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_41',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_42',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_43',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_44',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_45',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_46',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_47',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_48',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_49',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_50',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_51',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_52',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_53',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_54',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_55',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_56',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_57',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_58',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_59',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_60',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_sample_9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца коллекции'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Полное имя категории'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Полное имя коллекции'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Полное имя фирмы'),
        ),
    ]
