# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170417_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='samples_visible',
            field=models.IntegerField(default=0, verbose_name='Счётчик отображаемых образцов коллекции'),
        ),
    ]
