# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_collection_samples_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='img_sample_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 1 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_10',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 10 образца '),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_11',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 11 образца '),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 2 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 3 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_4',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 4 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_5',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 5 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_6',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 6 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_7',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 7 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_8',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 8 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_9',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 9 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 1 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 10 образца '),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_11',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 11 образца '),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 2 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 3 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 4 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 5 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 6 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 7 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 8 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 9 образца'),
        ),
    ]
