# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20170417_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='samples_visible',
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 1 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_10',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 10 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_11',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 11 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_12',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 12 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_13',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 13 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_14',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 14 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_15',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 15 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_16',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 16 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_17',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 17 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_18',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 18 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_19',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 19 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 2 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_20',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 20 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_21',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 21 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_22',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 22 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_23',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 23 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_24',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 24 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_25',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 25 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_26',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 26 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_27',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 27 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_28',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 28 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_29',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 29 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 3 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_30',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 30 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_31',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 31 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_32',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 32 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_33',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 33 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_34',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 35 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_35',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 35 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_36',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 36 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_37',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 37 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_38',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 38 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_39',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 39 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 4 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_40',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 40 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_41',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 41 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_42',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 42 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_43',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 43 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_44',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 44 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_45',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 45 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_46',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 46 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_47',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 47 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_48',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 48 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_49',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 49 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 5 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_50',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 50 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_51',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 51 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_52',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 52 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_53',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 53 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_54',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 54 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_56',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 56 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_57',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 57 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_58',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 58 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_59',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 59 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_6',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 6 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_60',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 60 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_7',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 7 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_8',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 8 образца'),
        ),
        migrations.AddField(
            model_name='collection',
            name='desc_sample_9',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание 9 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_12',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 12 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_13',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 13 образца '),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_14',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 14 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_15',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_16',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 16 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_17',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 17 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_18',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 18 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_19',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 19 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_20',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 20 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_21',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 21 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_22',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 22 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_23',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 23 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_24',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 24 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_25',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 25 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_26',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 26 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_27',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 27 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_28',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 28 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_29',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_30',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 30 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_31',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 31 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_32',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 32 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_33',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 33 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_34',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 34 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_35',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 35 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_36',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 36 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_37',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 37 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_38',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 38 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_39',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 39 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_40',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 40 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_41',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 41 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_42',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 42 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_43',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 43 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_44',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 44 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_45',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 45 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_46',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 46 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_47',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 47 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_48',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 48 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_49',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 49 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_50',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 50 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_51',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 51 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_52',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 52 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_53',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 53 бразца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_54',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_55',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 55 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_56',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 56 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_57',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 57 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_58',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 58 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_59',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 59 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='img_sample_60',
            field=models.FileField(blank=True, null=True, upload_to='uploads/samples', verbose_name='Картинка 60 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 12 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_13',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 13 образца '),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_14',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 14 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_15',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_16',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 16 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_17',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 17 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_18',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 18 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_19',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 19 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_20',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 20 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_21',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 21 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_22',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 22 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_23',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 23 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_24',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 24 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_25',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 25 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_26',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 26 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_27',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 27 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_28',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_29',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 29 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_30',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 30 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_31',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 31 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_32',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 32 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_33',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 33 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_34',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 34 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_35',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя  35 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_36',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 36 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_37',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 37 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_38',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 38 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_39',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 39 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_40',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 40 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_41',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 41 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_42',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 42 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_43',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 43 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_44',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 44 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_45',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 45 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_46',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 46 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_47',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 47 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_48',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 48 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_49',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 49 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_50',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 50 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_51',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 51 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_52',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 52 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_53',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 53 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_54',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_55',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 55 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_56',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 56 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_57',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 57 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_58',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 58 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_59',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 59 образца'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_sample_60',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя 60 образца'),
        ),
    ]
