# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170418_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('НПЛП', 'Напольные покрытия'), ('ПТЛС', 'Потолочные системы'), ('НСТП', 'Настенные покрытия'), ('ТКСТ', 'Текстиль')], default='НПЛП', max_length=4, verbose_name='Тип категории'),
        ),
    ]
