# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20170419_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('CC', 'Напольные покрытия'), ('CS', 'Потолочные системы'), ('WC', 'Настенные покрытия'), ('TT', 'Текстиль')], default='CC', max_length=4, verbose_name='Тип категории'),
        ),
    ]
