# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=24, null=True, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщения')),
                ('connected_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата, когда клиент пытался связаться связаться')),
            ],
        ),
    ]
