# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя проекта')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание проекта')),
                ('present_img', models.FileField(upload_to='uploads/projects', verbose_name='Главное изображение проекта')),
                ('img_1', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 1 проекта')),
                ('img_2', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 2 проекта')),
                ('img_3', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 3 проекта')),
                ('img_4', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 4 проекта')),
                ('img_5', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 5 проекта')),
                ('img_6', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 6 проекта')),
                ('img_7', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 7 проекта')),
                ('img_8', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 8 проекта')),
                ('img_9', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 9 проекта')),
                ('img_10', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 10 проекта')),
                ('img_11', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 11 проекта')),
                ('img_12', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 12 проекта')),
                ('img_13', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 13 проекта')),
                ('img_14', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 14 проекта')),
                ('img_15', models.FileField(blank=True, null=True, upload_to='uploads/projects', verbose_name='Изображение 15 проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
