# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_1', models.FileField(upload_to='uploads/slider/', verbose_name='1й слайд')),
                ('slide_2', models.FileField(upload_to='uploads/slider/', verbose_name='2й слайд')),
                ('slide_3', models.FileField(upload_to='uploads/slider/', verbose_name='3й слайд')),
                ('slide_4', models.FileField(upload_to='uploads/slider/', verbose_name='4й слайд')),
                ('slide_5', models.FileField(upload_to='uploads/slider/', verbose_name='5й слайд')),
                ('slide_6', models.FileField(upload_to='uploads/slider/', verbose_name='6й слайд')),
                ('slide_7', models.FileField(upload_to='uploads/slider/', verbose_name='7й слайд')),
                ('slide_8', models.FileField(upload_to='uploads/slider/', verbose_name='8й слайд')),
                ('slide_9', models.FileField(upload_to='uploads/slider/', verbose_name='9й слайд')),
                ('slide_10', models.FileField(upload_to='uploads/slider/', verbose_name='10й слайд')),
                ('slide_11', models.FileField(upload_to='uploads/slider/', verbose_name='11й слайд')),
                ('slide_12', models.FileField(upload_to='uploads/slider/', verbose_name='12й слайд')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
